// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// primSpanningTree
Rcpp::NumericMatrix primSpanningTree(int n);
RcppExport SEXP _auxiliarcpp_primSpanningTree(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(primSpanningTree(n));
    return rcpp_result_gen;
END_RCPP
}
// is_spanning_tree_cpp
bool is_spanning_tree_cpp(IntegerMatrix adj_matrix);
RcppExport SEXP _auxiliarcpp_is_spanning_tree_cpp(SEXP adj_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type adj_matrix(adj_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(is_spanning_tree_cpp(adj_matrix));
    return rcpp_result_gen;
END_RCPP
}
// corr_ar2_fast
arma::mat corr_ar2_fast(const int n, const double phi1, const double phi2, const bool use_clamp);
RcppExport SEXP _auxiliarcpp_corr_ar2_fast(SEXP nSEXP, SEXP phi1SEXP, SEXP phi2SEXP, SEXP use_clampSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< const double >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< const bool >::type use_clamp(use_clampSEXP);
    rcpp_result_gen = Rcpp::wrap(corr_ar2_fast(n, phi1, phi2, use_clamp));
    return rcpp_result_gen;
END_RCPP
}
// is_connected
bool is_connected(const NumericMatrix& adj_matrix);
RcppExport SEXP _auxiliarcpp_is_connected(SEXP adj_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type adj_matrix(adj_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(is_connected(adj_matrix));
    return rcpp_result_gen;
END_RCPP
}
// random_spanning_tree_prob_2
NumericMatrix random_spanning_tree_prob_2(NumericMatrix adj_matrix, double p);
RcppExport SEXP _auxiliarcpp_random_spanning_tree_prob_2(SEXP adj_matrixSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type adj_matrix(adj_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(random_spanning_tree_prob_2(adj_matrix, p));
    return rcpp_result_gen;
END_RCPP
}
// rowsums_mine
arma::vec rowsums_mine(const arma::mat& a);
RcppExport SEXP _auxiliarcpp_rowsums_mine(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(rowsums_mine(a));
    return rcpp_result_gen;
END_RCPP
}
// matrixb2_cpp
arma::mat matrixb2_cpp(arma::mat adjmatinf, double rho);
RcppExport SEXP _auxiliarcpp_matrixb2_cpp(SEXP adjmatinfSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixb2_cpp(adjmatinf, rho));
    return rcpp_result_gen;
END_RCPP
}
// ar1_correlation_matrix_2
arma::mat ar1_correlation_matrix_2(double phi, int lag);
RcppExport SEXP _auxiliarcpp_ar1_correlation_matrix_2(SEXP phiSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(ar1_correlation_matrix_2(phi, lag));
    return rcpp_result_gen;
END_RCPP
}
// matrixF_cpp
arma::mat matrixF_cpp(const arma::vec& nneigh, double rho);
RcppExport SEXP _auxiliarcpp_matrixF_cpp(SEXP nneighSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type nneigh(nneighSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixF_cpp(nneigh, rho));
    return rcpp_result_gen;
END_RCPP
}
// matrixFinv_cpp
arma::mat matrixFinv_cpp(const arma::vec& nneigh, double rho);
RcppExport SEXP _auxiliarcpp_matrixFinv_cpp(SEXP nneighSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type nneigh(nneighSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixFinv_cpp(nneigh, rho));
    return rcpp_result_gen;
END_RCPP
}
// varcovspadagar_cpp
arma::mat varcovspadagar_cpp(const arma::mat& adjmatinf, double rho);
RcppExport SEXP _auxiliarcpp_varcovspadagar_cpp(SEXP adjmatinfSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(varcovspadagar_cpp(adjmatinf, rho));
    return rcpp_result_gen;
END_RCPP
}
// trvarcovspadagar_cpp
double trvarcovspadagar_cpp(const arma::mat& adjmatinf, double rho);
RcppExport SEXP _auxiliarcpp_trvarcovspadagar_cpp(SEXP adjmatinfSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(trvarcovspadagar_cpp(adjmatinf, rho));
    return rcpp_result_gen;
END_RCPP
}
// varcovspacar_cpp
arma::mat varcovspacar_cpp(const arma::mat& adjmatinf, double rho);
RcppExport SEXP _auxiliarcpp_varcovspacar_cpp(SEXP adjmatinfSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(varcovspacar_cpp(adjmatinf, rho));
    return rcpp_result_gen;
END_RCPP
}
// varcovdagar_cpp
arma::mat varcovdagar_cpp(const arma::mat& adjmatinf, double rho, double sigma2, double tau2);
RcppExport SEXP _auxiliarcpp_varcovdagar_cpp(SEXP adjmatinfSEXP, SEXP rhoSEXP, SEXP sigma2SEXP, SEXP tau2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    rcpp_result_gen = Rcpp::wrap(varcovdagar_cpp(adjmatinf, rho, sigma2, tau2));
    return rcpp_result_gen;
END_RCPP
}
// vdagar_cpp
arma::mat vdagar_cpp(const arma::mat& adjmatinf, double rho, double psi);
RcppExport SEXP _auxiliarcpp_vdagar_cpp(SEXP adjmatinfSEXP, SEXP rhoSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(vdagar_cpp(adjmatinf, rho, psi));
    return rcpp_result_gen;
END_RCPP
}
// spatimecovar_2_cpp
arma::mat spatimecovar_2_cpp(int lag, const arma::mat& adjmatinf, double rho, double psi, double phi);
RcppExport SEXP _auxiliarcpp_spatimecovar_2_cpp(SEXP lagSEXP, SEXP adjmatinfSEXP, SEXP rhoSEXP, SEXP psiSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(spatimecovar_2_cpp(lag, adjmatinf, rho, psi, phi));
    return rcpp_result_gen;
END_RCPP
}
// sar_covariance_rcpp
arma::mat sar_covariance_rcpp(const arma::mat& A_or_W, const double rho, const bool is_W, const bool row_standardize, const bool return_precision);
RcppExport SEXP _auxiliarcpp_sar_covariance_rcpp(SEXP A_or_WSEXP, SEXP rhoSEXP, SEXP is_WSEXP, SEXP row_standardizeSEXP, SEXP return_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A_or_W(A_or_WSEXP);
    Rcpp::traits::input_parameter< const double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const bool >::type is_W(is_WSEXP);
    Rcpp::traits::input_parameter< const bool >::type row_standardize(row_standardizeSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_precision(return_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(sar_covariance_rcpp(A_or_W, rho, is_W, row_standardize, return_precision));
    return rcpp_result_gen;
END_RCPP
}
// spatimecovarsar_2_cpp
arma::mat spatimecovarsar_2_cpp(int lag, const arma::mat& adjmat, double rho, double psi, double phi);
RcppExport SEXP _auxiliarcpp_spatimecovarsar_2_cpp(SEXP lagSEXP, SEXP adjmatSEXP, SEXP rhoSEXP, SEXP psiSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmat(adjmatSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(spatimecovarsar_2_cpp(lag, adjmat, rho, psi, phi));
    return rcpp_result_gen;
END_RCPP
}
// spatimecovarsar_211_cpp
Rcpp::List spatimecovarsar_211_cpp(int lag, const arma::mat& adjmat, double rho, double psi, double phi);
RcppExport SEXP _auxiliarcpp_spatimecovarsar_211_cpp(SEXP lagSEXP, SEXP adjmatSEXP, SEXP rhoSEXP, SEXP psiSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmat(adjmatSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(spatimecovarsar_211_cpp(lag, adjmat, rho, psi, phi));
    return rcpp_result_gen;
END_RCPP
}
// spatimecovarsar_21_cpp
arma::mat spatimecovarsar_21_cpp(int lag, const arma::mat& adjmatinf, double rho, double psi, double phi);
RcppExport SEXP _auxiliarcpp_spatimecovarsar_21_cpp(SEXP lagSEXP, SEXP adjmatinfSEXP, SEXP rhoSEXP, SEXP psiSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(spatimecovarsar_21_cpp(lag, adjmatinf, rho, psi, phi));
    return rcpp_result_gen;
END_RCPP
}
// spatimecovar_ar2_cpp
arma::mat spatimecovar_ar2_cpp(int lag, const arma::mat& adjmatinf, double rho, double psi, double phi1, double phi2);
RcppExport SEXP _auxiliarcpp_spatimecovar_ar2_cpp(SEXP lagSEXP, SEXP adjmatinfSEXP, SEXP rhoSEXP, SEXP psiSEXP, SEXP phi1SEXP, SEXP phi2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< double >::type phi2(phi2SEXP);
    rcpp_result_gen = Rcpp::wrap(spatimecovar_ar2_cpp(lag, adjmatinf, rho, psi, phi1, phi2));
    return rcpp_result_gen;
END_RCPP
}
// spatimecovarsar_ar2_cpp
arma::mat spatimecovarsar_ar2_cpp(int lag, const arma::mat& adjmat, double rho, double psi, double phi1, double phi2);
RcppExport SEXP _auxiliarcpp_spatimecovarsar_ar2_cpp(SEXP lagSEXP, SEXP adjmatSEXP, SEXP rhoSEXP, SEXP psiSEXP, SEXP phi1SEXP, SEXP phi2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmat(adjmatSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< double >::type phi2(phi2SEXP);
    rcpp_result_gen = Rcpp::wrap(spatimecovarsar_ar2_cpp(lag, adjmat, rho, psi, phi1, phi2));
    return rcpp_result_gen;
END_RCPP
}
// spatimecovarsar_2_ar2_cpp
arma::mat spatimecovarsar_2_ar2_cpp(int lag, const arma::mat& adjmatinf, double rho, double psi, double phi1, double phi2);
RcppExport SEXP _auxiliarcpp_spatimecovarsar_2_ar2_cpp(SEXP lagSEXP, SEXP adjmatinfSEXP, SEXP rhoSEXP, SEXP psiSEXP, SEXP phi1SEXP, SEXP phi2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< double >::type phi2(phi2SEXP);
    rcpp_result_gen = Rcpp::wrap(spatimecovarsar_2_ar2_cpp(lag, adjmatinf, rho, psi, phi1, phi2));
    return rcpp_result_gen;
END_RCPP
}
// spatimecovarcar_2_cpp
arma::mat spatimecovarcar_2_cpp(int lag, const arma::mat& adjmatinf, double rho, double psi, double phi);
RcppExport SEXP _auxiliarcpp_spatimecovarcar_2_cpp(SEXP lagSEXP, SEXP adjmatinfSEXP, SEXP rhoSEXP, SEXP psiSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(spatimecovarcar_2_cpp(lag, adjmatinf, rho, psi, phi));
    return rcpp_result_gen;
END_RCPP
}
// spatimecovar_2_zero_cpp
arma::mat spatimecovar_2_zero_cpp(int lag, const arma::mat& adjmatinf, double rho, double phi);
RcppExport SEXP _auxiliarcpp_spatimecovar_2_zero_cpp(SEXP lagSEXP, SEXP adjmatinfSEXP, SEXP rhoSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(spatimecovar_2_zero_cpp(lag, adjmatinf, rho, phi));
    return rcpp_result_gen;
END_RCPP
}
// spatimecovar_cpp
arma::mat spatimecovar_cpp(int lag, const arma::mat& adjmatinf, double sigma2, double tau2, double phi, double rho);
RcppExport SEXP _auxiliarcpp_spatimecovar_cpp(SEXP lagSEXP, SEXP adjmatinfSEXP, SEXP sigma2SEXP, SEXP tau2SEXP, SEXP phiSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(spatimecovar_cpp(lag, adjmatinf, sigma2, tau2, phi, rho));
    return rcpp_result_gen;
END_RCPP
}
// dbeta_rep_cpp
double dbeta_rep_cpp(double x, double mu, double sigma2);
RcppExport SEXP _auxiliarcpp_dbeta_rep_cpp(SEXP xSEXP, SEXP muSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(dbeta_rep_cpp(x, mu, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// rbeta_rep_cpp
double rbeta_rep_cpp(double mu, double sigma2);
RcppExport SEXP _auxiliarcpp_rbeta_rep_cpp(SEXP muSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(rbeta_rep_cpp(mu, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// posteriorvar_cpp
double posteriorvar_cpp(const arma::vec& theta, const arma::mat& adjmatinf, const arma::mat& X, const arma::vec& y, const arma::vec& mutheta, const arma::vec& sigmatheta);
RcppExport SEXP _auxiliarcpp_posteriorvar_cpp(SEXP thetaSEXP, SEXP adjmatinfSEXP, SEXP XSEXP, SEXP ySEXP, SEXP muthetaSEXP, SEXP sigmathetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mutheta(muthetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigmatheta(sigmathetaSEXP);
    rcpp_result_gen = Rcpp::wrap(posteriorvar_cpp(theta, adjmatinf, X, y, mutheta, sigmatheta));
    return rcpp_result_gen;
END_RCPP
}
// posteriorvar2_cpp
double posteriorvar2_cpp(const arma::vec& theta, const arma::mat& adjmatinf, const arma::mat& X, const arma::vec& y, const arma::vec& mutheta, const arma::vec& sigmatheta);
RcppExport SEXP _auxiliarcpp_posteriorvar2_cpp(SEXP thetaSEXP, SEXP adjmatinfSEXP, SEXP XSEXP, SEXP ySEXP, SEXP muthetaSEXP, SEXP sigmathetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mutheta(muthetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigmatheta(sigmathetaSEXP);
    rcpp_result_gen = Rcpp::wrap(posteriorvar2_cpp(theta, adjmatinf, X, y, mutheta, sigmatheta));
    return rcpp_result_gen;
END_RCPP
}
// mdivide_right_spd_vector
arma::rowvec mdivide_right_spd_vector(const arma::rowvec& y, const arma::mat& A);
RcppExport SEXP _auxiliarcpp_mdivide_right_spd_vector(SEXP ySEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(mdivide_right_spd_vector(y, A));
    return rcpp_result_gen;
END_RCPP
}
// mdivide_right_spd
arma::mat mdivide_right_spd(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _auxiliarcpp_mdivide_right_spd(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(mdivide_right_spd(A, B));
    return rcpp_result_gen;
END_RCPP
}
// posterior_spatemp_cpp
double posterior_spatemp_cpp(const arma::vec& theta, const arma::mat& adjmatinf, int lag, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _auxiliarcpp_posterior_spatemp_cpp(SEXP thetaSEXP, SEXP adjmatinfSEXP, SEXP lagSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_spatemp_cpp(theta, adjmatinf, lag, X, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// posterior_spatempsar_cpp
double posterior_spatempsar_cpp(const arma::vec& theta, const arma::mat& adjmat, int lag, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _auxiliarcpp_posterior_spatempsar_cpp(SEXP thetaSEXP, SEXP adjmatSEXP, SEXP lagSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmat(adjmatSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_spatempsar_cpp(theta, adjmat, lag, X, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// dbeta_ab
double dbeta_ab(double y, double alpha, double beta, double a, double b, bool log_out);
RcppExport SEXP _auxiliarcpp_dbeta_ab(SEXP ySEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP aSEXP, SEXP bSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(dbeta_ab(y, alpha, beta, a, b, log_out));
    return rcpp_result_gen;
END_RCPP
}
// posterior_spatempcens_2_cpp
Rcpp::List posterior_spatempcens_2_cpp(const arma::vec& theta, const arma::mat& adjmatinf, int lag, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _auxiliarcpp_posterior_spatempcens_2_cpp(SEXP thetaSEXP, SEXP adjmatinfSEXP, SEXP lagSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_spatempcens_2_cpp(theta, adjmatinf, lag, X, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// posterior_spatempcenssar_2_cpp
Rcpp::List posterior_spatempcenssar_2_cpp(const arma::vec& theta, const arma::mat& adjmat, int lag, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _auxiliarcpp_posterior_spatempcenssar_2_cpp(SEXP thetaSEXP, SEXP adjmatSEXP, SEXP lagSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmat(adjmatSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_spatempcenssar_2_cpp(theta, adjmat, lag, X, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// posterior_spatempcens_ar2_cpp
Rcpp::List posterior_spatempcens_ar2_cpp(const arma::vec& theta, const arma::mat& adjmatinf, int lag, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _auxiliarcpp_posterior_spatempcens_ar2_cpp(SEXP thetaSEXP, SEXP adjmatinfSEXP, SEXP lagSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_spatempcens_ar2_cpp(theta, adjmatinf, lag, X, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// posterior_spatempcenssar_ar2_cpp
Rcpp::List posterior_spatempcenssar_ar2_cpp(const arma::vec& theta, const arma::mat& adjmat, int lag, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _auxiliarcpp_posterior_spatempcenssar_ar2_cpp(SEXP thetaSEXP, SEXP adjmatSEXP, SEXP lagSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmat(adjmatSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_spatempcenssar_ar2_cpp(theta, adjmat, lag, X, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// posterior_spatempcens_cpp
Rcpp::List posterior_spatempcens_cpp(const arma::vec& theta, const arma::mat& adjmatinf, int lag, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _auxiliarcpp_posterior_spatempcens_cpp(SEXP thetaSEXP, SEXP adjmatinfSEXP, SEXP lagSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_spatempcens_cpp(theta, adjmatinf, lag, X, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// posterior_spatempcenscar_cpp
Rcpp::List posterior_spatempcenscar_cpp(const arma::vec& theta, const arma::mat& adjmatinf, int lag, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _auxiliarcpp_posterior_spatempcenscar_cpp(SEXP thetaSEXP, SEXP adjmatinfSEXP, SEXP lagSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_spatempcenscar_cpp(theta, adjmatinf, lag, X, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// vector_to_matrix
arma::mat vector_to_matrix(const arma::vec& v, int nrows, int ncols);
RcppExport SEXP _auxiliarcpp_vector_to_matrix(SEXP vSEXP, SEXP nrowsSEXP, SEXP ncolsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    Rcpp::traits::input_parameter< int >::type ncols(ncolsSEXP);
    rcpp_result_gen = Rcpp::wrap(vector_to_matrix(v, nrows, ncols));
    return rcpp_result_gen;
END_RCPP
}
// posterior_spatempcens_zero_cpp
Rcpp::List posterior_spatempcens_zero_cpp(const arma::vec& theta, const arma::mat& adjmatinf, int lag, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _auxiliarcpp_posterior_spatempcens_zero_cpp(SEXP thetaSEXP, SEXP adjmatinfSEXP, SEXP lagSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_spatempcens_zero_cpp(theta, adjmatinf, lag, X, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// posterior_spatempcens_ar2_zero_cpp
Rcpp::List posterior_spatempcens_ar2_zero_cpp(const arma::vec& theta, const arma::mat& adjmatinf, int lag, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _auxiliarcpp_posterior_spatempcens_ar2_zero_cpp(SEXP thetaSEXP, SEXP adjmatinfSEXP, SEXP lagSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_spatempcens_ar2_zero_cpp(theta, adjmatinf, lag, X, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// posteriorvar3_cpp
double posteriorvar3_cpp(const arma::vec& theta, const arma::mat& adjmatinf, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _auxiliarcpp_posteriorvar3_cpp(SEXP thetaSEXP, SEXP adjmatinfSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(posteriorvar3_cpp(theta, adjmatinf, X, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// posteriorvar4_cpp
Rcpp::List posteriorvar4_cpp(const arma::vec& theta, const arma::mat& adjmatinf, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _auxiliarcpp_posteriorvar4_cpp(SEXP thetaSEXP, SEXP adjmatinfSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(posteriorvar4_cpp(theta, adjmatinf, X, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// compute_exponentiated_matrices
Rcpp::List compute_exponentiated_matrices(const arma::mat& A, int n);
RcppExport SEXP _auxiliarcpp_compute_exponentiated_matrices(SEXP ASEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_exponentiated_matrices(A, n));
    return rcpp_result_gen;
END_RCPP
}
// compute_minima_and_argmin
Rcpp::List compute_minima_and_argmin(const Rcpp::List& matrices);
RcppExport SEXP _auxiliarcpp_compute_minima_and_argmin(SEXP matricesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type matrices(matricesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_minima_and_argmin(matrices));
    return rcpp_result_gen;
END_RCPP
}
// compute_argmin_only
arma::mat compute_argmin_only(const Rcpp::List& matrices);
RcppExport SEXP _auxiliarcpp_compute_argmin_only(SEXP matricesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type matrices(matricesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_argmin_only(matrices));
    return rcpp_result_gen;
END_RCPP
}
// compute_squared_exponentiated_matrices
Rcpp::List compute_squared_exponentiated_matrices(const arma::mat& A, int n);
RcppExport SEXP _auxiliarcpp_compute_squared_exponentiated_matrices(SEXP ASEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_squared_exponentiated_matrices(A, n));
    return rcpp_result_gen;
END_RCPP
}
// compute_argmin_only_2
arma::mat compute_argmin_only_2(const Rcpp::List& matrices);
RcppExport SEXP _auxiliarcpp_compute_argmin_only_2(SEXP matricesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type matrices(matricesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_argmin_only_2(matrices));
    return rcpp_result_gen;
END_RCPP
}
// difference
double difference(int i, int j, const Rcpp::List& WFval, int n);
RcppExport SEXP _auxiliarcpp_difference(SEXP iSEXP, SEXP jSEXP, SEXP WFvalSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type WFval(WFvalSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(difference(i, j, WFval, n));
    return rcpp_result_gen;
END_RCPP
}
// generate_random_spanning_tree_optimized
arma::mat generate_random_spanning_tree_optimized(const arma::mat& adj_matrix);
RcppExport SEXP _auxiliarcpp_generate_random_spanning_tree_optimized(SEXP adj_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adj_matrix(adj_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_random_spanning_tree_optimized(adj_matrix));
    return rcpp_result_gen;
END_RCPP
}
// generate_random_spanning_tree_and_probability
Rcpp::List generate_random_spanning_tree_and_probability(const arma::mat& weight_matrix);
RcppExport SEXP _auxiliarcpp_generate_random_spanning_tree_and_probability(SEXP weight_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type weight_matrix(weight_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_random_spanning_tree_and_probability(weight_matrix));
    return rcpp_result_gen;
END_RCPP
}
// generate_random_spanning_tree_and_log_probability
Rcpp::List generate_random_spanning_tree_and_log_probability(const arma::mat& weight_matrix);
RcppExport SEXP _auxiliarcpp_generate_random_spanning_tree_and_log_probability(SEXP weight_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type weight_matrix(weight_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_random_spanning_tree_and_log_probability(weight_matrix));
    return rcpp_result_gen;
END_RCPP
}
// jaccard_similarity
double jaccard_similarity(const arma::mat& adj1, const arma::mat& adj2);
RcppExport SEXP _auxiliarcpp_jaccard_similarity(SEXP adj1SEXP, SEXP adj2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adj1(adj1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adj2(adj2SEXP);
    rcpp_result_gen = Rcpp::wrap(jaccard_similarity(adj1, adj2));
    return rcpp_result_gen;
END_RCPP
}
// bayestrandgrap_cpp
List bayestrandgrap_cpp(const arma::vec& y, const arma::mat& xobs, const arma::vec& thetaini, int iter, int burn, int thin, const arma::mat& weight_mat, const arma::vec& aprior, const arma::vec& bprior, double divproprho, double divproppsi);
RcppExport SEXP _auxiliarcpp_bayestrandgrap_cpp(SEXP ySEXP, SEXP xobsSEXP, SEXP thetainiSEXP, SEXP iterSEXP, SEXP burnSEXP, SEXP thinSEXP, SEXP weight_matSEXP, SEXP apriorSEXP, SEXP bpriorSEXP, SEXP divproprhoSEXP, SEXP divproppsiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xobs(xobsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type thetaini(thetainiSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type weight_mat(weight_matSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type aprior(apriorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type bprior(bpriorSEXP);
    Rcpp::traits::input_parameter< double >::type divproprho(divproprhoSEXP);
    Rcpp::traits::input_parameter< double >::type divproppsi(divproppsiSEXP);
    rcpp_result_gen = Rcpp::wrap(bayestrandgrap_cpp(y, xobs, thetaini, iter, burn, thin, weight_mat, aprior, bprior, divproprho, divproppsi));
    return rcpp_result_gen;
END_RCPP
}
// generate_weighted_spanning_tree_aldous_broder_optimized
Rcpp::List generate_weighted_spanning_tree_aldous_broder_optimized(const arma::mat& weight_matrix);
RcppExport SEXP _auxiliarcpp_generate_weighted_spanning_tree_aldous_broder_optimized(SEXP weight_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type weight_matrix(weight_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_weighted_spanning_tree_aldous_broder_optimized(weight_matrix));
    return rcpp_result_gen;
END_RCPP
}
// generate_weighted_spanning_tree_aldous_broder_optimized_2
Rcpp::List generate_weighted_spanning_tree_aldous_broder_optimized_2(const arma::mat& weight_matrix);
RcppExport SEXP _auxiliarcpp_generate_weighted_spanning_tree_aldous_broder_optimized_2(SEXP weight_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type weight_matrix(weight_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_weighted_spanning_tree_aldous_broder_optimized_2(weight_matrix));
    return rcpp_result_gen;
END_RCPP
}
// loglikespatemp_cpp
arma::vec loglikespatemp_cpp(List listres, const arma::mat& Xmat, const arma::vec& y, int lags);
RcppExport SEXP _auxiliarcpp_loglikespatemp_cpp(SEXP listresSEXP, SEXP XmatSEXP, SEXP ySEXP, SEXP lagsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type listres(listresSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type lags(lagsSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikespatemp_cpp(listres, Xmat, y, lags));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_ar1_fast_pkg_cpp
double log_likelihood_ar1_fast_pkg_cpp(const arma::mat& x, const arma::vec& y, const arma::ivec& cc, int lag, const arma::mat& adjmatinf, const arma::vec& theta, const arma::vec& lower, const arma::vec& upper, std::string pkg, std::string fun_name);
RcppExport SEXP _auxiliarcpp_log_likelihood_ar1_fast_pkg_cpp(SEXP xSEXP, SEXP ySEXP, SEXP ccSEXP, SEXP lagSEXP, SEXP adjmatinfSEXP, SEXP thetaSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP pkgSEXP, SEXP fun_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type cc(ccSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< std::string >::type pkg(pkgSEXP);
    Rcpp::traits::input_parameter< std::string >::type fun_name(fun_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_ar1_fast_pkg_cpp(x, y, cc, lag, adjmatinf, theta, lower, upper, pkg, fun_name));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_ar2_fast_pkg_cpp
double log_likelihood_ar2_fast_pkg_cpp(const arma::mat& x, const arma::vec& y, const arma::ivec& cc, int lag, const arma::mat& adjmatinf, const arma::vec& theta, const arma::vec& lower, const arma::vec& upper, std::string pkg, std::string fun_name);
RcppExport SEXP _auxiliarcpp_log_likelihood_ar2_fast_pkg_cpp(SEXP xSEXP, SEXP ySEXP, SEXP ccSEXP, SEXP lagSEXP, SEXP adjmatinfSEXP, SEXP thetaSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP pkgSEXP, SEXP fun_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type cc(ccSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< std::string >::type pkg(pkgSEXP);
    Rcpp::traits::input_parameter< std::string >::type fun_name(fun_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_ar2_fast_pkg_cpp(x, y, cc, lag, adjmatinf, theta, lower, upper, pkg, fun_name));
    return rcpp_result_gen;
END_RCPP
}
// spatimecovarcar_cpp
arma::mat spatimecovarcar_cpp(const arma::mat& adjmatinf, const arma::mat& Wt, const double rho_s, const double rho_t, const double rho_st, const double psi);
RcppExport SEXP _auxiliarcpp_spatimecovarcar_cpp(SEXP adjmatinfSEXP, SEXP WtSEXP, SEXP rho_sSEXP, SEXP rho_tSEXP, SEXP rho_stSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Wt(WtSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_s(rho_sSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_t(rho_tSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_st(rho_stSEXP);
    Rcpp::traits::input_parameter< const double >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(spatimecovarcar_cpp(adjmatinf, Wt, rho_s, rho_t, rho_st, psi));
    return rcpp_result_gen;
END_RCPP
}
// spatimecovarcar_zero_cpp
arma::mat spatimecovarcar_zero_cpp(const arma::mat& adjmatinf, const arma::mat& Wt, const double rho_s, const double rho_t, const double rho_st);
RcppExport SEXP _auxiliarcpp_spatimecovarcar_zero_cpp(SEXP adjmatinfSEXP, SEXP WtSEXP, SEXP rho_sSEXP, SEXP rho_tSEXP, SEXP rho_stSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Wt(WtSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_s(rho_sSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_t(rho_tSEXP);
    Rcpp::traits::input_parameter< const double >::type rho_st(rho_stSEXP);
    rcpp_result_gen = Rcpp::wrap(spatimecovarcar_zero_cpp(adjmatinf, Wt, rho_s, rho_t, rho_st));
    return rcpp_result_gen;
END_RCPP
}
// posterior_spatempcenscar2_cpp
Rcpp::List posterior_spatempcenscar2_cpp(const arma::vec& theta, const arma::mat& adjmatinf, const arma::mat& Wt, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b, const arma::vec& alim, const arma::vec& blim);
RcppExport SEXP _auxiliarcpp_posterior_spatempcenscar2_cpp(SEXP thetaSEXP, SEXP adjmatinfSEXP, SEXP WtSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP, SEXP alimSEXP, SEXP blimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Wt(WtSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alim(alimSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type blim(blimSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_spatempcenscar2_cpp(theta, adjmatinf, Wt, X, y, a, b, alim, blim));
    return rcpp_result_gen;
END_RCPP
}
// posterior_spatempcenscar_zero_cpp
Rcpp::List posterior_spatempcenscar_zero_cpp(const arma::vec& theta, const arma::mat& adjmatinf, const arma::mat& Wt, const arma::mat& X, const arma::vec& y, const arma::vec& a, const arma::vec& b, const arma::vec& alim, const arma::vec& blim);
RcppExport SEXP _auxiliarcpp_posterior_spatempcenscar_zero_cpp(SEXP thetaSEXP, SEXP adjmatinfSEXP, SEXP WtSEXP, SEXP XSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP, SEXP alimSEXP, SEXP blimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Wt(WtSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alim(alimSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type blim(blimSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_spatempcenscar_zero_cpp(theta, adjmatinf, Wt, X, y, a, b, alim, blim));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_car_fast_cpp
double log_likelihood_car_fast_cpp(const arma::mat& x, const arma::vec& y, const arma::ivec& cc, const int lag, const arma::mat& adj_matcom, const arma::vec& theta, const arma::vec& lower, const arma::vec& upper, const double jitter, const double min_prob);
RcppExport SEXP _auxiliarcpp_log_likelihood_car_fast_cpp(SEXP xSEXP, SEXP ySEXP, SEXP ccSEXP, SEXP lagSEXP, SEXP adj_matcomSEXP, SEXP thetaSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP jitterSEXP, SEXP min_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type cc(ccSEXP);
    Rcpp::traits::input_parameter< const int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adj_matcom(adj_matcomSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const double >::type jitter(jitterSEXP);
    Rcpp::traits::input_parameter< const double >::type min_prob(min_probSEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_car_fast_cpp(x, y, cc, lag, adj_matcom, theta, lower, upper, jitter, min_prob));
    return rcpp_result_gen;
END_RCPP
}
// pred_dist_spatempcens_ind_cpp
arma::vec pred_dist_spatempcens_ind_cpp(const arma::vec& theta, Rcpp::Nullable<Rcpp::IntegerVector> predind, const arma::mat& Xmat, arma::vec ytotobs, const int lags, const arma::ivec& indicens, arma::mat adjmatinf);
RcppExport SEXP _auxiliarcpp_pred_dist_spatempcens_ind_cpp(SEXP thetaSEXP, SEXP predindSEXP, SEXP XmatSEXP, SEXP ytotobsSEXP, SEXP lagsSEXP, SEXP indicensSEXP, SEXP adjmatinfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type predind(predindSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ytotobs(ytotobsSEXP);
    Rcpp::traits::input_parameter< const int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type indicens(indicensSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type adjmatinf(adjmatinfSEXP);
    rcpp_result_gen = Rcpp::wrap(pred_dist_spatempcens_ind_cpp(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf));
    return rcpp_result_gen;
END_RCPP
}
// pred_dist_spatempcens_ar2_ind_cpp
arma::vec pred_dist_spatempcens_ar2_ind_cpp(const arma::vec& theta, Rcpp::Nullable<Rcpp::IntegerVector> predind, const arma::mat& Xmat, arma::vec ytotobs, const int lags, arma::ivec indicens, arma::mat adjmatinf);
RcppExport SEXP _auxiliarcpp_pred_dist_spatempcens_ar2_ind_cpp(SEXP thetaSEXP, SEXP predindSEXP, SEXP XmatSEXP, SEXP ytotobsSEXP, SEXP lagsSEXP, SEXP indicensSEXP, SEXP adjmatinfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type predind(predindSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ytotobs(ytotobsSEXP);
    Rcpp::traits::input_parameter< const int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type indicens(indicensSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type adjmatinf(adjmatinfSEXP);
    rcpp_result_gen = Rcpp::wrap(pred_dist_spatempcens_ar2_ind_cpp(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf));
    return rcpp_result_gen;
END_RCPP
}
// pred_dist_spatempcens_car_ind_cpp
arma::vec pred_dist_spatempcens_car_ind_cpp(const arma::vec& theta, Rcpp::Nullable<Rcpp::IntegerVector> predind, const arma::mat& Xmat, arma::vec ytotobs, const int lags, const arma::ivec& indicens, const arma::mat& adjmatinf);
RcppExport SEXP _auxiliarcpp_pred_dist_spatempcens_car_ind_cpp(SEXP thetaSEXP, SEXP predindSEXP, SEXP XmatSEXP, SEXP ytotobsSEXP, SEXP lagsSEXP, SEXP indicensSEXP, SEXP adjmatinfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type predind(predindSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ytotobs(ytotobsSEXP);
    Rcpp::traits::input_parameter< const int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type indicens(indicensSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    rcpp_result_gen = Rcpp::wrap(pred_dist_spatempcens_car_ind_cpp(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf));
    return rcpp_result_gen;
END_RCPP
}
// pred_dens_spatempcens_ind_cpp
double pred_dens_spatempcens_ind_cpp(const arma::vec& theta, Rcpp::Nullable<Rcpp::IntegerVector> predind, const arma::mat& Xmat, arma::vec ytotobs, const int lags, const arma::ivec& indicens, arma::mat adjmatinf, const arma::vec& ynew, const bool logd);
RcppExport SEXP _auxiliarcpp_pred_dens_spatempcens_ind_cpp(SEXP thetaSEXP, SEXP predindSEXP, SEXP XmatSEXP, SEXP ytotobsSEXP, SEXP lagsSEXP, SEXP indicensSEXP, SEXP adjmatinfSEXP, SEXP ynewSEXP, SEXP logdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type predind(predindSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ytotobs(ytotobsSEXP);
    Rcpp::traits::input_parameter< const int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type indicens(indicensSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ynew(ynewSEXP);
    Rcpp::traits::input_parameter< const bool >::type logd(logdSEXP);
    rcpp_result_gen = Rcpp::wrap(pred_dens_spatempcens_ind_cpp(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew, logd));
    return rcpp_result_gen;
END_RCPP
}
// pred_dens_spatempcens_car_ind_cpp
double pred_dens_spatempcens_car_ind_cpp(const arma::vec& theta, Rcpp::Nullable<Rcpp::IntegerVector> predind, const arma::mat& Xmat, arma::vec ytotobs, const int lags, const arma::ivec& indicens, const arma::mat& adjmatinf, const arma::vec& ynew, const bool logd);
RcppExport SEXP _auxiliarcpp_pred_dens_spatempcens_car_ind_cpp(SEXP thetaSEXP, SEXP predindSEXP, SEXP XmatSEXP, SEXP ytotobsSEXP, SEXP lagsSEXP, SEXP indicensSEXP, SEXP adjmatinfSEXP, SEXP ynewSEXP, SEXP logdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type predind(predindSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ytotobs(ytotobsSEXP);
    Rcpp::traits::input_parameter< const int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type indicens(indicensSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ynew(ynewSEXP);
    Rcpp::traits::input_parameter< const bool >::type logd(logdSEXP);
    rcpp_result_gen = Rcpp::wrap(pred_dens_spatempcens_car_ind_cpp(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew, logd));
    return rcpp_result_gen;
END_RCPP
}
// pred_dens_spatempcens_ar2_ind_cpp
double pred_dens_spatempcens_ar2_ind_cpp(const arma::vec& theta, Rcpp::Nullable<Rcpp::IntegerVector> predind, const arma::mat& Xmat, arma::vec ytotobs, const int lags, arma::ivec indicens, arma::mat adjmatinf, const arma::vec& ynew, const bool logd);
RcppExport SEXP _auxiliarcpp_pred_dens_spatempcens_ar2_ind_cpp(SEXP thetaSEXP, SEXP predindSEXP, SEXP XmatSEXP, SEXP ytotobsSEXP, SEXP lagsSEXP, SEXP indicensSEXP, SEXP adjmatinfSEXP, SEXP ynewSEXP, SEXP logdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type predind(predindSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ytotobs(ytotobsSEXP);
    Rcpp::traits::input_parameter< const int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type indicens(indicensSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ynew(ynewSEXP);
    Rcpp::traits::input_parameter< const bool >::type logd(logdSEXP);
    rcpp_result_gen = Rcpp::wrap(pred_dens_spatempcens_ar2_ind_cpp(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew, logd));
    return rcpp_result_gen;
END_RCPP
}
// pred_pointwise_logdens_ar2_ind_cpp
arma::vec pred_pointwise_logdens_ar2_ind_cpp(const arma::vec& theta, const Rcpp::IntegerVector& predind, const arma::mat& Xmat, arma::vec ytotobs, const int lags, arma::ivec indicens, arma::mat adjmatinf, const arma::vec& ynew);
RcppExport SEXP _auxiliarcpp_pred_pointwise_logdens_ar2_ind_cpp(SEXP thetaSEXP, SEXP predindSEXP, SEXP XmatSEXP, SEXP ytotobsSEXP, SEXP lagsSEXP, SEXP indicensSEXP, SEXP adjmatinfSEXP, SEXP ynewSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type predind(predindSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ytotobs(ytotobsSEXP);
    Rcpp::traits::input_parameter< const int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type indicens(indicensSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ynew(ynewSEXP);
    rcpp_result_gen = Rcpp::wrap(pred_pointwise_logdens_ar2_ind_cpp(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew));
    return rcpp_result_gen;
END_RCPP
}
// pred_pointwise_logdens_ar1_ind_cpp
arma::vec pred_pointwise_logdens_ar1_ind_cpp(const arma::vec& theta, const Rcpp::IntegerVector& predind, const arma::mat& Xmat, arma::vec ytotobs, const int lags, arma::ivec indicens, arma::mat adjmatinf, const arma::vec& ynew);
RcppExport SEXP _auxiliarcpp_pred_pointwise_logdens_ar1_ind_cpp(SEXP thetaSEXP, SEXP predindSEXP, SEXP XmatSEXP, SEXP ytotobsSEXP, SEXP lagsSEXP, SEXP indicensSEXP, SEXP adjmatinfSEXP, SEXP ynewSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type predind(predindSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ytotobs(ytotobsSEXP);
    Rcpp::traits::input_parameter< const int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type indicens(indicensSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ynew(ynewSEXP);
    rcpp_result_gen = Rcpp::wrap(pred_pointwise_logdens_ar1_ind_cpp(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew));
    return rcpp_result_gen;
END_RCPP
}
// pred_pointwise_logdens_car_ind_cpp
arma::vec pred_pointwise_logdens_car_ind_cpp(const arma::vec& theta, const Rcpp::IntegerVector& predind, const arma::mat& Xmat, arma::vec ytotobs, const int lags, arma::ivec indicens, arma::mat adjmatinf, const arma::vec& ynew);
RcppExport SEXP _auxiliarcpp_pred_pointwise_logdens_car_ind_cpp(SEXP thetaSEXP, SEXP predindSEXP, SEXP XmatSEXP, SEXP ytotobsSEXP, SEXP lagsSEXP, SEXP indicensSEXP, SEXP adjmatinfSEXP, SEXP ynewSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type predind(predindSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ytotobs(ytotobsSEXP);
    Rcpp::traits::input_parameter< const int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type indicens(indicensSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type adjmatinf(adjmatinfSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ynew(ynewSEXP);
    rcpp_result_gen = Rcpp::wrap(pred_pointwise_logdens_car_ind_cpp(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_auxiliarcpp_primSpanningTree", (DL_FUNC) &_auxiliarcpp_primSpanningTree, 1},
    {"_auxiliarcpp_is_spanning_tree_cpp", (DL_FUNC) &_auxiliarcpp_is_spanning_tree_cpp, 1},
    {"_auxiliarcpp_corr_ar2_fast", (DL_FUNC) &_auxiliarcpp_corr_ar2_fast, 4},
    {"_auxiliarcpp_is_connected", (DL_FUNC) &_auxiliarcpp_is_connected, 1},
    {"_auxiliarcpp_random_spanning_tree_prob_2", (DL_FUNC) &_auxiliarcpp_random_spanning_tree_prob_2, 2},
    {"_auxiliarcpp_rowsums_mine", (DL_FUNC) &_auxiliarcpp_rowsums_mine, 1},
    {"_auxiliarcpp_matrixb2_cpp", (DL_FUNC) &_auxiliarcpp_matrixb2_cpp, 2},
    {"_auxiliarcpp_ar1_correlation_matrix_2", (DL_FUNC) &_auxiliarcpp_ar1_correlation_matrix_2, 2},
    {"_auxiliarcpp_matrixF_cpp", (DL_FUNC) &_auxiliarcpp_matrixF_cpp, 2},
    {"_auxiliarcpp_matrixFinv_cpp", (DL_FUNC) &_auxiliarcpp_matrixFinv_cpp, 2},
    {"_auxiliarcpp_varcovspadagar_cpp", (DL_FUNC) &_auxiliarcpp_varcovspadagar_cpp, 2},
    {"_auxiliarcpp_trvarcovspadagar_cpp", (DL_FUNC) &_auxiliarcpp_trvarcovspadagar_cpp, 2},
    {"_auxiliarcpp_varcovspacar_cpp", (DL_FUNC) &_auxiliarcpp_varcovspacar_cpp, 2},
    {"_auxiliarcpp_varcovdagar_cpp", (DL_FUNC) &_auxiliarcpp_varcovdagar_cpp, 4},
    {"_auxiliarcpp_vdagar_cpp", (DL_FUNC) &_auxiliarcpp_vdagar_cpp, 3},
    {"_auxiliarcpp_spatimecovar_2_cpp", (DL_FUNC) &_auxiliarcpp_spatimecovar_2_cpp, 5},
    {"_auxiliarcpp_sar_covariance_rcpp", (DL_FUNC) &_auxiliarcpp_sar_covariance_rcpp, 5},
    {"_auxiliarcpp_spatimecovarsar_2_cpp", (DL_FUNC) &_auxiliarcpp_spatimecovarsar_2_cpp, 5},
    {"_auxiliarcpp_spatimecovarsar_211_cpp", (DL_FUNC) &_auxiliarcpp_spatimecovarsar_211_cpp, 5},
    {"_auxiliarcpp_spatimecovarsar_21_cpp", (DL_FUNC) &_auxiliarcpp_spatimecovarsar_21_cpp, 5},
    {"_auxiliarcpp_spatimecovar_ar2_cpp", (DL_FUNC) &_auxiliarcpp_spatimecovar_ar2_cpp, 6},
    {"_auxiliarcpp_spatimecovarsar_ar2_cpp", (DL_FUNC) &_auxiliarcpp_spatimecovarsar_ar2_cpp, 6},
    {"_auxiliarcpp_spatimecovarsar_2_ar2_cpp", (DL_FUNC) &_auxiliarcpp_spatimecovarsar_2_ar2_cpp, 6},
    {"_auxiliarcpp_spatimecovarcar_2_cpp", (DL_FUNC) &_auxiliarcpp_spatimecovarcar_2_cpp, 5},
    {"_auxiliarcpp_spatimecovar_2_zero_cpp", (DL_FUNC) &_auxiliarcpp_spatimecovar_2_zero_cpp, 4},
    {"_auxiliarcpp_spatimecovar_cpp", (DL_FUNC) &_auxiliarcpp_spatimecovar_cpp, 6},
    {"_auxiliarcpp_dbeta_rep_cpp", (DL_FUNC) &_auxiliarcpp_dbeta_rep_cpp, 3},
    {"_auxiliarcpp_rbeta_rep_cpp", (DL_FUNC) &_auxiliarcpp_rbeta_rep_cpp, 2},
    {"_auxiliarcpp_posteriorvar_cpp", (DL_FUNC) &_auxiliarcpp_posteriorvar_cpp, 6},
    {"_auxiliarcpp_posteriorvar2_cpp", (DL_FUNC) &_auxiliarcpp_posteriorvar2_cpp, 6},
    {"_auxiliarcpp_mdivide_right_spd_vector", (DL_FUNC) &_auxiliarcpp_mdivide_right_spd_vector, 2},
    {"_auxiliarcpp_mdivide_right_spd", (DL_FUNC) &_auxiliarcpp_mdivide_right_spd, 2},
    {"_auxiliarcpp_posterior_spatemp_cpp", (DL_FUNC) &_auxiliarcpp_posterior_spatemp_cpp, 7},
    {"_auxiliarcpp_posterior_spatempsar_cpp", (DL_FUNC) &_auxiliarcpp_posterior_spatempsar_cpp, 7},
    {"_auxiliarcpp_dbeta_ab", (DL_FUNC) &_auxiliarcpp_dbeta_ab, 6},
    {"_auxiliarcpp_posterior_spatempcens_2_cpp", (DL_FUNC) &_auxiliarcpp_posterior_spatempcens_2_cpp, 7},
    {"_auxiliarcpp_posterior_spatempcenssar_2_cpp", (DL_FUNC) &_auxiliarcpp_posterior_spatempcenssar_2_cpp, 7},
    {"_auxiliarcpp_posterior_spatempcens_ar2_cpp", (DL_FUNC) &_auxiliarcpp_posterior_spatempcens_ar2_cpp, 7},
    {"_auxiliarcpp_posterior_spatempcenssar_ar2_cpp", (DL_FUNC) &_auxiliarcpp_posterior_spatempcenssar_ar2_cpp, 7},
    {"_auxiliarcpp_posterior_spatempcens_cpp", (DL_FUNC) &_auxiliarcpp_posterior_spatempcens_cpp, 7},
    {"_auxiliarcpp_posterior_spatempcenscar_cpp", (DL_FUNC) &_auxiliarcpp_posterior_spatempcenscar_cpp, 7},
    {"_auxiliarcpp_vector_to_matrix", (DL_FUNC) &_auxiliarcpp_vector_to_matrix, 3},
    {"_auxiliarcpp_posterior_spatempcens_zero_cpp", (DL_FUNC) &_auxiliarcpp_posterior_spatempcens_zero_cpp, 7},
    {"_auxiliarcpp_posterior_spatempcens_ar2_zero_cpp", (DL_FUNC) &_auxiliarcpp_posterior_spatempcens_ar2_zero_cpp, 7},
    {"_auxiliarcpp_posteriorvar3_cpp", (DL_FUNC) &_auxiliarcpp_posteriorvar3_cpp, 6},
    {"_auxiliarcpp_posteriorvar4_cpp", (DL_FUNC) &_auxiliarcpp_posteriorvar4_cpp, 6},
    {"_auxiliarcpp_compute_exponentiated_matrices", (DL_FUNC) &_auxiliarcpp_compute_exponentiated_matrices, 2},
    {"_auxiliarcpp_compute_minima_and_argmin", (DL_FUNC) &_auxiliarcpp_compute_minima_and_argmin, 1},
    {"_auxiliarcpp_compute_argmin_only", (DL_FUNC) &_auxiliarcpp_compute_argmin_only, 1},
    {"_auxiliarcpp_compute_squared_exponentiated_matrices", (DL_FUNC) &_auxiliarcpp_compute_squared_exponentiated_matrices, 2},
    {"_auxiliarcpp_compute_argmin_only_2", (DL_FUNC) &_auxiliarcpp_compute_argmin_only_2, 1},
    {"_auxiliarcpp_difference", (DL_FUNC) &_auxiliarcpp_difference, 4},
    {"_auxiliarcpp_generate_random_spanning_tree_optimized", (DL_FUNC) &_auxiliarcpp_generate_random_spanning_tree_optimized, 1},
    {"_auxiliarcpp_generate_random_spanning_tree_and_probability", (DL_FUNC) &_auxiliarcpp_generate_random_spanning_tree_and_probability, 1},
    {"_auxiliarcpp_generate_random_spanning_tree_and_log_probability", (DL_FUNC) &_auxiliarcpp_generate_random_spanning_tree_and_log_probability, 1},
    {"_auxiliarcpp_jaccard_similarity", (DL_FUNC) &_auxiliarcpp_jaccard_similarity, 2},
    {"_auxiliarcpp_bayestrandgrap_cpp", (DL_FUNC) &_auxiliarcpp_bayestrandgrap_cpp, 11},
    {"_auxiliarcpp_generate_weighted_spanning_tree_aldous_broder_optimized", (DL_FUNC) &_auxiliarcpp_generate_weighted_spanning_tree_aldous_broder_optimized, 1},
    {"_auxiliarcpp_generate_weighted_spanning_tree_aldous_broder_optimized_2", (DL_FUNC) &_auxiliarcpp_generate_weighted_spanning_tree_aldous_broder_optimized_2, 1},
    {"_auxiliarcpp_loglikespatemp_cpp", (DL_FUNC) &_auxiliarcpp_loglikespatemp_cpp, 4},
    {"_auxiliarcpp_log_likelihood_ar1_fast_pkg_cpp", (DL_FUNC) &_auxiliarcpp_log_likelihood_ar1_fast_pkg_cpp, 10},
    {"_auxiliarcpp_log_likelihood_ar2_fast_pkg_cpp", (DL_FUNC) &_auxiliarcpp_log_likelihood_ar2_fast_pkg_cpp, 10},
    {"_auxiliarcpp_spatimecovarcar_cpp", (DL_FUNC) &_auxiliarcpp_spatimecovarcar_cpp, 6},
    {"_auxiliarcpp_spatimecovarcar_zero_cpp", (DL_FUNC) &_auxiliarcpp_spatimecovarcar_zero_cpp, 5},
    {"_auxiliarcpp_posterior_spatempcenscar2_cpp", (DL_FUNC) &_auxiliarcpp_posterior_spatempcenscar2_cpp, 9},
    {"_auxiliarcpp_posterior_spatempcenscar_zero_cpp", (DL_FUNC) &_auxiliarcpp_posterior_spatempcenscar_zero_cpp, 9},
    {"_auxiliarcpp_log_likelihood_car_fast_cpp", (DL_FUNC) &_auxiliarcpp_log_likelihood_car_fast_cpp, 10},
    {"_auxiliarcpp_pred_dist_spatempcens_ind_cpp", (DL_FUNC) &_auxiliarcpp_pred_dist_spatempcens_ind_cpp, 7},
    {"_auxiliarcpp_pred_dist_spatempcens_ar2_ind_cpp", (DL_FUNC) &_auxiliarcpp_pred_dist_spatempcens_ar2_ind_cpp, 7},
    {"_auxiliarcpp_pred_dist_spatempcens_car_ind_cpp", (DL_FUNC) &_auxiliarcpp_pred_dist_spatempcens_car_ind_cpp, 7},
    {"_auxiliarcpp_pred_dens_spatempcens_ind_cpp", (DL_FUNC) &_auxiliarcpp_pred_dens_spatempcens_ind_cpp, 9},
    {"_auxiliarcpp_pred_dens_spatempcens_car_ind_cpp", (DL_FUNC) &_auxiliarcpp_pred_dens_spatempcens_car_ind_cpp, 9},
    {"_auxiliarcpp_pred_dens_spatempcens_ar2_ind_cpp", (DL_FUNC) &_auxiliarcpp_pred_dens_spatempcens_ar2_ind_cpp, 9},
    {"_auxiliarcpp_pred_pointwise_logdens_ar2_ind_cpp", (DL_FUNC) &_auxiliarcpp_pred_pointwise_logdens_ar2_ind_cpp, 8},
    {"_auxiliarcpp_pred_pointwise_logdens_ar1_ind_cpp", (DL_FUNC) &_auxiliarcpp_pred_pointwise_logdens_ar1_ind_cpp, 8},
    {"_auxiliarcpp_pred_pointwise_logdens_car_ind_cpp", (DL_FUNC) &_auxiliarcpp_pred_pointwise_logdens_car_ind_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_auxiliarcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
