#' @useDynLib auxiliarcpp, .registration = TRUE
#' @import Rcpp
#' @rawNamespace export(spatimecovarsar_21_cpp)
#' @rawNamespace export(spatimecovarsar_ar2_cpp)
#' @rawNamespace export(spatimecovar_ar2_cpp)
#' @rawNamespace export(log_likelihood_ar2_fast_pkg_cpp)
#' @rawNamespace export(log_likelihood_ar1_fast_pkg_cpp)
#' @rawNamespace export(spatimecovarsar_2_ar2_cpp)
#' @rawNamespace export(spatimecovarsar_2_cpp)
#' @rawNamespace export(spatimecovarcar_cpp)
#' @rawNamespace export(spatimecovarsar_211_cpp)
#' @rawNamespace export(corr_ar2_fast)
#' @rawNamespace export(sar_covariance_rcpp)
#' @rawNamespace export(posterior_spatempcenscar2_cpp)
#' @rawNamespace export(spatimecovarcar_zero_cpp)
#' @rawNamespace export(posterior_spatempcenscar_zero_cpp)
#' @rawNamespace export(spatimecovarcar_zero_cpp)
#' @rawNamespace export(log_likelihood_car_fast_cpp)
#' @rawNamespace export(pred_dist_spatempcens_ind_cpp)
#' @rawNamespace export(pred_dist_spatempcens_car_ind_cpp)
#' @rawNamespace export(pred_dist_spatempcens_ar2_ind_cpp)
#' @rawNamespace export(pred_dens_spatempcens_ind_cpp)
#' @rawNamespace export(pred_dens_spatempcens_ar2_ind_cpp)
#' @rawNamespace export(pred_dens_spatempcens_car_ind_cpp)
#' @rawNamespace export(pred_pointwise_logdens_ar2_ind_cpp)
#' @rawNamespace export(pred_pointwise_logdens_ar1_ind_cpp)
#' @rawNamespace export(pred_pointwise_logdens_car_ind_cpp)
NULL
