# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#'@useDynLib auxiliarcpp, .registration = TRUE
NULL

#'@useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

#' @useDynLib auxiliarcpp, .registration = TRUE
NULL

primSpanningTree <- function(n) {
    .Call(`_auxiliarcpp_primSpanningTree`, n)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
is_spanning_tree_cpp <- function(adj_matrix) {
    .Call(`_auxiliarcpp_is_spanning_tree_cpp`, adj_matrix)
}

corr_ar2_fast <- function(n, phi1, phi2, use_clamp = TRUE) {
    .Call(`_auxiliarcpp_corr_ar2_fast`, n, phi1, phi2, use_clamp)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
is_connected <- function(adj_matrix) {
    .Call(`_auxiliarcpp_is_connected`, adj_matrix)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
random_spanning_tree_prob_2 <- function(adj_matrix, p) {
    .Call(`_auxiliarcpp_random_spanning_tree_prob_2`, adj_matrix, p)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
rowsums_mine <- function(a) {
    .Call(`_auxiliarcpp_rowsums_mine`, a)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
matrixb2_cpp <- function(adjmatinf, rho) {
    .Call(`_auxiliarcpp_matrixb2_cpp`, adjmatinf, rho)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
ar1_correlation_matrix_2 <- function(phi, lag) {
    .Call(`_auxiliarcpp_ar1_correlation_matrix_2`, phi, lag)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
matrixF_cpp <- function(nneigh, rho) {
    .Call(`_auxiliarcpp_matrixF_cpp`, nneigh, rho)
}

#' @export
matrixFinv_cpp <- function(nneigh, rho) {
    .Call(`_auxiliarcpp_matrixFinv_cpp`, nneigh, rho)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
varcovspadagar_cpp <- function(adjmatinf, rho) {
    .Call(`_auxiliarcpp_varcovspadagar_cpp`, adjmatinf, rho)
}

trvarcovspadagar_cpp <- function(adjmatinf, rho) {
    .Call(`_auxiliarcpp_trvarcovspadagar_cpp`, adjmatinf, rho)
}

varcovspacar_cpp <- function(adjmatinf, rho) {
    .Call(`_auxiliarcpp_varcovspacar_cpp`, adjmatinf, rho)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
varcovdagar_cpp <- function(adjmatinf, rho, sigma2, tau2) {
    .Call(`_auxiliarcpp_varcovdagar_cpp`, adjmatinf, rho, sigma2, tau2)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
vdagar_cpp <- function(adjmatinf, rho, psi) {
    .Call(`_auxiliarcpp_vdagar_cpp`, adjmatinf, rho, psi)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
spatimecovar_2_cpp <- function(lag, adjmatinf, rho, psi, phi) {
    .Call(`_auxiliarcpp_spatimecovar_2_cpp`, lag, adjmatinf, rho, psi, phi)
}

sar_covariance_rcpp <- function(A_or_W, rho, is_W = FALSE, row_standardize = FALSE, return_precision = FALSE) {
    .Call(`_auxiliarcpp_sar_covariance_rcpp`, A_or_W, rho, is_W, row_standardize, return_precision)
}

spatimecovarsar_2_cpp <- function(lag, adjmat, rho, psi, phi) {
    .Call(`_auxiliarcpp_spatimecovarsar_2_cpp`, lag, adjmat, rho, psi, phi)
}

spatimecovarsar_211_cpp <- function(lag, adjmat, rho, psi, phi) {
    .Call(`_auxiliarcpp_spatimecovarsar_211_cpp`, lag, adjmat, rho, psi, phi)
}

spatimecovarsar_21_cpp <- function(lag, adjmatinf, rho, psi, phi) {
    .Call(`_auxiliarcpp_spatimecovarsar_21_cpp`, lag, adjmatinf, rho, psi, phi)
}

spatimecovar_ar2_cpp <- function(lag, adjmatinf, rho, psi, phi1, phi2) {
    .Call(`_auxiliarcpp_spatimecovar_ar2_cpp`, lag, adjmatinf, rho, psi, phi1, phi2)
}

spatimecovarsar_ar2_cpp <- function(lag, adjmat, rho, psi, phi1, phi2) {
    .Call(`_auxiliarcpp_spatimecovarsar_ar2_cpp`, lag, adjmat, rho, psi, phi1, phi2)
}

spatimecovarsar_2_ar2_cpp <- function(lag, adjmatinf, rho, psi, phi1, phi2) {
    .Call(`_auxiliarcpp_spatimecovarsar_2_ar2_cpp`, lag, adjmatinf, rho, psi, phi1, phi2)
}

spatimecovarcar_2_cpp <- function(lag, adjmatinf, rho, psi, phi) {
    .Call(`_auxiliarcpp_spatimecovarcar_2_cpp`, lag, adjmatinf, rho, psi, phi)
}

spatimecovar_2_zero_cpp <- function(lag, adjmatinf, rho, phi) {
    .Call(`_auxiliarcpp_spatimecovar_2_zero_cpp`, lag, adjmatinf, rho, phi)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
spatimecovar_cpp <- function(lag, adjmatinf, sigma2, tau2, phi, rho) {
    .Call(`_auxiliarcpp_spatimecovar_cpp`, lag, adjmatinf, sigma2, tau2, phi, rho)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
dbeta_rep_cpp <- function(x, mu, sigma2) {
    .Call(`_auxiliarcpp_dbeta_rep_cpp`, x, mu, sigma2)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
rbeta_rep_cpp <- function(mu, sigma2) {
    .Call(`_auxiliarcpp_rbeta_rep_cpp`, mu, sigma2)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
posteriorvar_cpp <- function(theta, adjmatinf, X, y, mutheta, sigmatheta) {
    .Call(`_auxiliarcpp_posteriorvar_cpp`, theta, adjmatinf, X, y, mutheta, sigmatheta)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
posteriorvar2_cpp <- function(theta, adjmatinf, X, y, mutheta, sigmatheta) {
    .Call(`_auxiliarcpp_posteriorvar2_cpp`, theta, adjmatinf, X, y, mutheta, sigmatheta)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
mdivide_right_spd_vector <- function(y, A) {
    .Call(`_auxiliarcpp_mdivide_right_spd_vector`, y, A)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
mdivide_right_spd <- function(A, B) {
    .Call(`_auxiliarcpp_mdivide_right_spd`, A, B)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
posterior_spatemp_cpp <- function(theta, adjmatinf, lag, X, y, a, b) {
    .Call(`_auxiliarcpp_posterior_spatemp_cpp`, theta, adjmatinf, lag, X, y, a, b)
}

posterior_spatempsar_cpp <- function(theta, adjmat, lag, X, y, a, b) {
    .Call(`_auxiliarcpp_posterior_spatempsar_cpp`, theta, adjmat, lag, X, y, a, b)
}

dbeta_ab <- function(y, alpha, beta, a, b, log_out = FALSE) {
    .Call(`_auxiliarcpp_dbeta_ab`, y, alpha, beta, a, b, log_out)
}

posterior_spatempcens_2_cpp <- function(theta, adjmatinf, lag, X, y, a, b) {
    .Call(`_auxiliarcpp_posterior_spatempcens_2_cpp`, theta, adjmatinf, lag, X, y, a, b)
}

posterior_spatempcenssar_2_cpp <- function(theta, adjmat, lag, X, y, a, b) {
    .Call(`_auxiliarcpp_posterior_spatempcenssar_2_cpp`, theta, adjmat, lag, X, y, a, b)
}

posterior_spatempcens_ar2_cpp <- function(theta, adjmatinf, lag, X, y, a, b) {
    .Call(`_auxiliarcpp_posterior_spatempcens_ar2_cpp`, theta, adjmatinf, lag, X, y, a, b)
}

posterior_spatempcenssar_ar2_cpp <- function(theta, adjmat, lag, X, y, a, b) {
    .Call(`_auxiliarcpp_posterior_spatempcenssar_ar2_cpp`, theta, adjmat, lag, X, y, a, b)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
posterior_spatempcens_cpp <- function(theta, adjmatinf, lag, X, y, a, b) {
    .Call(`_auxiliarcpp_posterior_spatempcens_cpp`, theta, adjmatinf, lag, X, y, a, b)
}

posterior_spatempcenscar_cpp <- function(theta, adjmatinf, lag, X, y, a, b) {
    .Call(`_auxiliarcpp_posterior_spatempcenscar_cpp`, theta, adjmatinf, lag, X, y, a, b)
}

vector_to_matrix <- function(v, nrows, ncols) {
    .Call(`_auxiliarcpp_vector_to_matrix`, v, nrows, ncols)
}

posterior_spatempcens_zero_cpp <- function(theta, adjmatinf, lag, X, y, a, b) {
    .Call(`_auxiliarcpp_posterior_spatempcens_zero_cpp`, theta, adjmatinf, lag, X, y, a, b)
}

posterior_spatempcens_ar2_zero_cpp <- function(theta, adjmatinf, lag, X, y, a, b) {
    .Call(`_auxiliarcpp_posterior_spatempcens_ar2_zero_cpp`, theta, adjmatinf, lag, X, y, a, b)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
posteriorvar3_cpp <- function(theta, adjmatinf, X, y, a, b) {
    .Call(`_auxiliarcpp_posteriorvar3_cpp`, theta, adjmatinf, X, y, a, b)
}

posteriorvar4_cpp <- function(theta, adjmatinf, X, y, a, b) {
    .Call(`_auxiliarcpp_posteriorvar4_cpp`, theta, adjmatinf, X, y, a, b)
}

#' @export
compute_exponentiated_matrices <- function(A, n) {
    .Call(`_auxiliarcpp_compute_exponentiated_matrices`, A, n)
}

#' @export
compute_minima_and_argmin <- function(matrices) {
    .Call(`_auxiliarcpp_compute_minima_and_argmin`, matrices)
}

#' @export
compute_argmin_only <- function(matrices) {
    .Call(`_auxiliarcpp_compute_argmin_only`, matrices)
}

#' @export
compute_squared_exponentiated_matrices <- function(A, n) {
    .Call(`_auxiliarcpp_compute_squared_exponentiated_matrices`, A, n)
}

#' @export
compute_argmin_only_2 <- function(matrices) {
    .Call(`_auxiliarcpp_compute_argmin_only_2`, matrices)
}

#' @export
difference <- function(i, j, WFval, n) {
    .Call(`_auxiliarcpp_difference`, i, j, WFval, n)
}

#' @export
generate_random_spanning_tree_optimized <- function(adj_matrix) {
    .Call(`_auxiliarcpp_generate_random_spanning_tree_optimized`, adj_matrix)
}

#' @export
generate_random_spanning_tree_and_probability <- function(weight_matrix) {
    .Call(`_auxiliarcpp_generate_random_spanning_tree_and_probability`, weight_matrix)
}

#' @export
generate_random_spanning_tree_and_log_probability <- function(weight_matrix) {
    .Call(`_auxiliarcpp_generate_random_spanning_tree_and_log_probability`, weight_matrix)
}

#' @export
jaccard_similarity <- function(adj1, adj2) {
    .Call(`_auxiliarcpp_jaccard_similarity`, adj1, adj2)
}

#' @export
bayestrandgrap_cpp <- function(y, xobs, thetaini, iter, burn, thin, weight_mat, aprior, bprior, divproprho = 18, divproppsi = 20) {
    .Call(`_auxiliarcpp_bayestrandgrap_cpp`, y, xobs, thetaini, iter, burn, thin, weight_mat, aprior, bprior, divproprho, divproppsi)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
generate_weighted_spanning_tree_aldous_broder_optimized <- function(weight_matrix) {
    .Call(`_auxiliarcpp_generate_weighted_spanning_tree_aldous_broder_optimized`, weight_matrix)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
generate_weighted_spanning_tree_aldous_broder_optimized_2 <- function(weight_matrix) {
    .Call(`_auxiliarcpp_generate_weighted_spanning_tree_aldous_broder_optimized_2`, weight_matrix)
}

#' @useDynLib auxiliarcpp, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#' @export
loglikespatemp_cpp <- function(listres, Xmat, y, lags) {
    .Call(`_auxiliarcpp_loglikespatemp_cpp`, listres, Xmat, y, lags)
}

log_likelihood_ar1_fast_pkg_cpp <- function(x, y, cc, lag, adjmatinf, theta, lower, upper, pkg, fun_name = "spatimecovar_2_cpp") {
    .Call(`_auxiliarcpp_log_likelihood_ar1_fast_pkg_cpp`, x, y, cc, lag, adjmatinf, theta, lower, upper, pkg, fun_name)
}

log_likelihood_ar2_fast_pkg_cpp <- function(x, y, cc, lag, adjmatinf, theta, lower, upper, pkg, fun_name = "spatimecovar_ar2_cpp") {
    .Call(`_auxiliarcpp_log_likelihood_ar2_fast_pkg_cpp`, x, y, cc, lag, adjmatinf, theta, lower, upper, pkg, fun_name)
}

spatimecovarcar_cpp <- function(adjmatinf, Wt, rho_s, rho_t, rho_st, psi) {
    .Call(`_auxiliarcpp_spatimecovarcar_cpp`, adjmatinf, Wt, rho_s, rho_t, rho_st, psi)
}

spatimecovarcar_zero_cpp <- function(adjmatinf, Wt, rho_s, rho_t, rho_st) {
    .Call(`_auxiliarcpp_spatimecovarcar_zero_cpp`, adjmatinf, Wt, rho_s, rho_t, rho_st)
}

posterior_spatempcenscar2_cpp <- function(theta, adjmatinf, Wt, X, y, a, b, alim, blim) {
    .Call(`_auxiliarcpp_posterior_spatempcenscar2_cpp`, theta, adjmatinf, Wt, X, y, a, b, alim, blim)
}

posterior_spatempcenscar_zero_cpp <- function(theta, adjmatinf, Wt, X, y, a, b, alim, blim) {
    .Call(`_auxiliarcpp_posterior_spatempcenscar_zero_cpp`, theta, adjmatinf, Wt, X, y, a, b, alim, blim)
}

log_likelihood_car_fast_cpp <- function(x, y, cc, lag, adj_matcom, theta, lower, upper, jitter = 1e-10, min_prob = 1e-300) {
    .Call(`_auxiliarcpp_log_likelihood_car_fast_cpp`, x, y, cc, lag, adj_matcom, theta, lower, upper, jitter, min_prob)
}

pred_dist_spatempcens_ind_cpp <- function(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf) {
    .Call(`_auxiliarcpp_pred_dist_spatempcens_ind_cpp`, theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf)
}

pred_dist_spatempcens_ar2_ind_cpp <- function(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf) {
    .Call(`_auxiliarcpp_pred_dist_spatempcens_ar2_ind_cpp`, theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf)
}

pred_dist_spatempcens_car_ind_cpp <- function(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf) {
    .Call(`_auxiliarcpp_pred_dist_spatempcens_car_ind_cpp`, theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf)
}

pred_dens_spatempcens_ind_cpp <- function(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew, logd = TRUE) {
    .Call(`_auxiliarcpp_pred_dens_spatempcens_ind_cpp`, theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew, logd)
}

pred_dens_spatempcens_car_ind_cpp <- function(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew, logd = TRUE) {
    .Call(`_auxiliarcpp_pred_dens_spatempcens_car_ind_cpp`, theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew, logd)
}

pred_dens_spatempcens_ar2_ind_cpp <- function(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew, logd = TRUE) {
    .Call(`_auxiliarcpp_pred_dens_spatempcens_ar2_ind_cpp`, theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew, logd)
}

pred_pointwise_logdens_ar2_ind_cpp <- function(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew) {
    .Call(`_auxiliarcpp_pred_pointwise_logdens_ar2_ind_cpp`, theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew)
}

pred_pointwise_logdens_ar1_ind_cpp <- function(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew) {
    .Call(`_auxiliarcpp_pred_pointwise_logdens_ar1_ind_cpp`, theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew)
}

pred_pointwise_logdens_car_ind_cpp <- function(theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew) {
    .Call(`_auxiliarcpp_pred_pointwise_logdens_car_ind_cpp`, theta, predind, Xmat, ytotobs, lags, indicens, adjmatinf, ynew)
}

